### ISSUE TITLE
Service Port registers as Vendor 1286 Device 8174

### ISSUE THREAD

**Issue by rbeesley** [coggy9/HKHacking#1]
I'm pretty sure my device has updated, so this may not be useful any more.

https://devicehunt.com/view/type/usb/vendor/1286/device/8174

It's possible that with the Marvell Windows Driver referenced in the manual that we could get more traction. It looks like the 88DE3006 is the SOC providing Firmware and Serial connectivity. There also seems to be a Debug port, maybe JTAG?

I see in init.rc that `start adbd` is commented out, which is too bad. That might have been a really convenient way to connect to the device.

Providing this issue if this is information you'd like to capture in documentation.

**Comment by coggy9** [comment]
The link you included just seems to list random Radeon drivers.

AFAIK, the service port only responds to the usb_boot executable included with the reflashing package that Harman uses, which I have put in [releases](https://github.com/coggy9/HKHacking/releases). That gets you a telnet/serial console with the U-Boot bootloader. I've been trying to dump the NAND, but been having issues with areas not reading out correctly, requiring redumps.

**Comment by rbeesley** [comment]
Yeah, the page wasn't listed because it provided drivers. It was just to document the vendor and device ids.
