### ISSUE TITLE
Comprehensive instructions for missed OTA update

### ISSUE THREAD

**Issue by ehilst515** [coggy9/HKHacking#10]
My parents had an Invoke device that they unplugged and abandoned once they read that the speaker would lose Cortana and no longer be supported. I now have possession of the Invoke that's unusable due to missing the OTA update. When I turn it on, it says to use Cortana to set up, which is of course now impossible. Everything I am able to find on this also says to update the software to keep using it as a Bluetooth speaker.

With my limited understanding, I am assuming the [flashing tools](https://github.com/coggy9/HKHacking/discussions/3) released in this project along with the [Barracuda_libre-12.2050.3.release](https://github.com/coggy9/HKHacking/discussions/9) update package will allow me to upgrade the software and then use it as a Bluetooth speaker, as long as the Invoke is currently on 11.1842.0. Is this true? If so, could I make a PR with a "Missed OTA V12 Upgrade.md" to list out all of the instructions on what to do if you missed the OTA update and want to use an Invoke as a BT speaker for @coggy9 to review?

**Comment by coggy9** [comment]
The discussion for the 12.2050.3 release only has the delta update file, which can't be applied, but once I confirm a file someone just sent me, literally a few minutes ago, isn't a virus/a bricking OTA, it'll be updated with the full OTA and reflashing tools.

**Comment by coggy9** [comment]
It's legit, you can find it [here](https://github.com/coggy9/HKHacking/releases/tag/FinalOTA).
